spring:
  datasource:
    url: jdbc:h2:mem:credit_request_system_db
    password: 1234
    username: matheus
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    show-sql: true